"""Stage: propose new anchor_radii by splitting bottleneck/imbalanced anchors."""

from ._config import C, paths
from .report import collect_crossing_stats


def _propose_anchor_radii(rows, radii, imbalance_ratio, min_gap):
    """
    Inspect per-anchor crossing rows and propose new radii by inserting
    midpoints next to bottleneck or imbalanced anchors.
    Returns (new_radii_sorted, list_of_decisions).
    """
    n = len(radii)
    inserts = set()
    decisions = []

    def gap(a, b):
        return radii[b] - radii[a] if 0 <= a < n and 0 <= b < n else 0.0

    for i, r in enumerate(rows):
        if r['flag'] == 'NO DATA':
            decisions.append((i, 'no data', None))
            continue

        total, inner, outer = r['total'], r['inner'], r['outer']
        is_bottleneck = total < C.bottleneck_threshold

        if min(inner, outer) == 0 and total > 0:
            ratio = float('inf')
        else:
            ratio = max(inner, outer) / max(min(inner, outer), 1)
        is_imbalanced = ratio > imbalance_ratio

        if not (is_bottleneck or is_imbalanced):
            decisions.append((i, 'ok', None))
            continue

        # Decide which side to split.
        # Imbalance: inner >> outer means few outer crossings → split outward gap.
        # outer >> inner means few inner crossings → split inward gap.
        # Bottleneck (balanced): split the wider neighbor gap.
        inner_gap = gap(i - 1, i)
        outer_gap = gap(i, i + 1)
        choices = []
        if outer > inner:
            choices = [('inner_gap', i - 1, i, inner_gap),
                       ('outer_gap', i, i + 1, outer_gap)]
        elif inner > outer:
            choices = [('outer_gap', i, i + 1, outer_gap),
                       ('inner_gap', i - 1, i, inner_gap)]
        else:
            if outer_gap >= inner_gap:
                choices = [('outer_gap', i, i + 1, outer_gap),
                           ('inner_gap', i - 1, i, inner_gap)]
            else:
                choices = [('inner_gap', i - 1, i, inner_gap),
                           ('outer_gap', i, i + 1, outer_gap)]

        chosen = None
        for label, a, b, g in choices:
            if a < 0 or b >= n:
                continue
            # 1e-9 tolerance — radii like 1.0-0.9 evaluate to 0.0999...8 in
            # float, which would otherwise read as "narrower than 2*min_gap"
            # even when they're nominally identical to the next gap.
            if g < 2 * min_gap - 1e-9:
                continue
            new_r = round((radii[a] + radii[b]) / 2, 4)
            if new_r in inserts or new_r in radii:
                continue
            chosen = (label, new_r, g)
            inserts.add(new_r)
            break

        reason = 'bottleneck' if is_bottleneck else f'imbalance({inner}/{outer})'
        if chosen is None:
            decisions.append((i, f'{reason}: no room (min_gap={min_gap})', None))
        else:
            label, new_r, g = chosen
            decisions.append((i, f'{reason}: split {label} ({g:.3f}nm)', new_r))

    new_radii = sorted(set(list(radii) + list(inserts)))
    return new_radii, decisions


def stage_adjust(args):
    P = paths()
    radii = list(C.anchor_radii)
    rows = collect_crossing_stats()

    if all(r['flag'] == 'NO DATA' for r in rows):
        print('[adjust] no benchmark data found — run benchmark + report first')
        return

    new_radii, decisions = _propose_anchor_radii(
        rows, radii,
        imbalance_ratio=C.adjust_imbalance_ratio,
        min_gap=C.adjust_min_gap_nm,
    )

    print(f"\n  {'Anchor':>6}  {'Radius':>7}  {'Total':>6}  {'I/O':>9}  Decision")
    print('  ' + '─' * 60)
    for r, (i, reason, new_r) in zip(rows, decisions):
        io = f"{r['inner']}/{r['outer']}"
        suffix = f"  -> insert at {new_r}" if new_r is not None else ''
        print(f"  {i:>6}  {r['radius']:>7.2f}  {r['total']:>6}  {io:>9}  "
              f"{reason}{suffix}")

    n_inserts = sum(1 for _, _, r in decisions if r is not None)
    print(f"\n[adjust] {n_inserts} anchor(s) to insert "
          f"({len(radii)} -> {len(new_radii)})")
    print(f"[adjust] new anchor_radii: {new_radii}")

    out_yml = P.work / 'anchor_radii_adjusted.yml'
    yaml_text = (
        f'# Generated by stage_adjust on benchmark crossing stats.\n'
        f'# Bottleneck threshold: {C.bottleneck_threshold}, '
        f'imbalance ratio: {C.adjust_imbalance_ratio}, '
        f'min gap: {C.adjust_min_gap_nm} nm.\n'
        f'# Original ({len(radii)} anchors):\n'
        f'#   {radii}\n'
        f'# Proposed ({len(new_radii)} anchors):\n'
        f'anchor_radii:\n'
    )
    yaml_text += ''.join(f'  - {r}\n' for r in new_radii)
    out_yml.write_text(yaml_text)
    print(f'[adjust] wrote {out_yml}')
    print('[adjust] To apply: copy the anchor_radii block into config.yml,\n'
          '         delete work_<name>/root/, and re-run from --stage setup.')
