"""
Stage: run Browndye2 b-surface trajectories for the BD/k_on contribution.

Prerequisites:
  - bd_enabled=True + bd_receptor_pqr / bd_ligand_pqr set in config.yml
    (typically pointing at receptor.pqr / ligand.pqr generated by the
    tutorial-side bd_prep.py helper)
  - setup has run, so root/model.xml exists and seekr2.prepare has built
    root/b_surface/ (auto-created when browndye_settings_input was non-None
    at prepare time)
  - browndye2 binaries discoverable — either on PATH or via
    `bd_binary_directory` in config.yml

The stage delegates to `seekr2.run.run(model, 'b_surface', ...)`, which
runs APBS to compute electrostatic grids, builds the BD reaction xml, and
launches `nam_simulation` for the configured number of trajectories. After
this completes, `swarmflow kinetics` will incorporate the b-surface escape
probabilities to compute k_on and ΔG_bind from k_on/k_off.
"""

import contextlib
import os
from pathlib import Path

from ._config import C, paths


@contextlib.contextmanager
def _bd_path_shim():
    """Prepend bd_binary_directory to PATH so browndye2 helpers (bd_top,
    surface_spheres, nam_simulation, ...) shell-call each other correctly
    even when the user hasn't put the bin dir on their PATH."""
    bin_dir = getattr(C, 'bd_binary_directory', '') or ''
    if not bin_dir:
        yield
        return
    saved = os.environ.get('PATH', '')
    os.environ['PATH'] = f'{bin_dir}:{saved}' if saved else bin_dir
    try:
        yield
    finally:
        os.environ['PATH'] = saved


def stage_bd(args):
    P = paths()
    root_xml = P.root / 'model.xml'
    assert root_xml.exists(), \
        'Run --stage setup first (no root/model.xml — setup builds it via seekr2.prepare)'

    if not getattr(C, 'bd_enabled', False):
        print('[bd] bd_enabled=False — skipping (set bd_enabled: true in '
              'config.yml to run BD)')
        return

    b_surface_dir = P.root / 'b_surface'
    if not b_surface_dir.exists():
        print(f'[bd] {b_surface_dir} not found — re-run setup with bd_enabled=True '
              'and bd_receptor_pqr/bd_ligand_pqr pointing at valid PQR files')
        return

    # Idempotency: skip if any non-empty resultsN.xml exists (seekr2 numbers
    # outputs as results1.xml, results2.xml, ...).
    existing = [p for p in b_surface_dir.glob('results*.xml')
                if p.stat().st_size > 0]
    if existing and not getattr(args, 'force_overwrite', False):
        print(f'[bd] {len(existing)} results*.xml already in {b_surface_dir} '
              f'— skipping (use --force-overwrite to re-run)')
        return

    import seekr2.modules.common_base as base
    import seekr2.run as sr_run

    curdir = os.getcwd()
    os.chdir(P.root)
    try:
        model = base.load_model('model.xml')
        n_traj = int(C.bd_num_b_surface_trajectories)
        n_threads = int(getattr(C, 'bd_n_threads', 1))
        print(f'[bd] running b_surface: {n_traj:,} trajectories on '
              f'{n_threads} thread(s)')
        with _bd_path_shim():
            sr_run.run(
                model,
                'b_surface',
                min_b_surface_simulation_length=n_traj,
                force_overwrite=getattr(args, 'force_overwrite', False),
                n_threads=n_threads,
            )
    finally:
        os.chdir(curdir)

    print(f'[bd] done — b_surface results in {b_surface_dir}. '
          f'Run --stage kinetics to fold k_on into ΔG_bind.')
